---
- name: this playbook install the package with handlers
  hosts: web
  become: true
  tasks:
    - name: installing packages httpd
      yum:
        name: httpd
        state: installed
      notify: httpd services starting
  handlers:
    - name: httpd services starting
      service:
        name: httpd
        state: started
